#!/usr/bin/sh

sxhkd &
polybar pimpbar &
feh --bg-scale ~/.config/wallpapers/gin.jpg &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_modifier     shift
bspc config focused_border_color "#dfdfdf"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
